---
driver_plugin: vagrant
driver_config:
  network:
    - ["forwarded_port", {guest: 8080, host: 8080, auto_correct: true}]

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 12.21.26

platforms:
  - name: ubuntu-16.04
    run_list:
      - recipe[apt::default]

suites:
- name: default
  run_list:
    - recipe[influxdb]
    - recipe[kapacitor-test]
    - recipe[curl]
  attributes:
    kapacitor:
      config:
        hostname: localhost
      version: '1.5.2'
      release: '1'
      mem_alert:
        crit: 90
